### ISSUE TITLE
Add bootstrap classes to application.html.erb

### ISSUE THREAD

**Issue by leefreemanxyz** [Winkeltje84/toc_bears#15]
Update your "application.html.erb" file with bootstrap classes to create the main structure to be shared by your views

**Comment by Woulei** [comment]
Devided the layouts into 2 options.

1.  application.html.erb for the event wireframe (includes navbar and footer)
2. jombotron.html.erb for the homepage wireframe (doesn't have navbar and footer and will be one big jumbotron)

We will have to tell rails which layout to use in the routes.
Maybe rename the jumbotron.html.erb

**Comment by Woulei** [comment]
Merged
