### ISSUE TITLE
Create an Event model

### ISSUE THREAD

**Issue by Winkeltje84** [Winkeltje84/toc_bears#6]
that has:
 - [x] a title
 - [ ] image
 - [x] location
 - [x] spaces available
 - [ ] workshop
 - [ ] sponsor
 - [x] Also add a boolean to indicate whether it is a public or an in-company event

**Comment by Woulei** [comment]
Did not make the associations with the workshop and sponsor yet. Rails won't allow me because they don't exist yet. Need to do that later. Same for the image.
